.org 00h		; power up and reset vector
	ljmp start

.org 100h
start:
	mov r0, #0h
	loop:
		inc r0
		lcall load_val
		lcall update_dac
		sjmp loop

load_val:
	mov dptr, sintable
	mov a, r0
	movc a, @a + dptr
	ret

update_dac:
	mov dptr, #0FE**h
	movx @dptr, a
	ret

  pop dph ; get the pc into the dptr
  pop dpl ; so we can find the sin table
  movc a, @a + dptr ; get the value from the able and put in a
  mov dptr, #0fe10h ; set up the dptr for the dac
  mov b, #10 ; divide the value by 10 as part of our extension
  div ab ; perform the actual division
  movx @dptr, a ; store the value in the dac
  ljmp loop ; go back to the top of the loop
	

; ############################################################
; Autogenerated sin table made in python
; ############################################################

sintable:
	.db #07fh, #082h, #085h, #088h, #08bh, #08fh, #092h, #095h, 
	.db #098h, #09bh, #09eh, #0a1h, #0a4h, #0a7h, #0aah, #0adh, 
	.db #0b0h, #0b3h, #0b6h, #0b8h, #0bbh, #0beh, #0c1h, #0c3h, 
	.db #0c6h, #0c8h, #0cbh, #0cdh, #0d0h, #0d2h, #0d5h, #0d7h, 
	.db #0d9h, #0dbh, #0ddh, #0e0h, #0e2h, #0e4h, #0e5h, #0e7h, 
	.db #0e9h, #0ebh, #0ech, #0eeh, #0efh, #0f1h, #0f2h, #0f4h, 
	.db #0f5h, #0f6h, #0f7h, #0f8h, #0f9h, #0fah, #0fbh, #0fbh, 
	.db #0fch, #0fdh, #0fdh, #0feh, #0feh, #0feh, #0feh, #0feh, 
	.db #0ffh, #0feh, #0feh, #0feh, #0feh, #0feh, #0fdh, #0fdh, 
	.db #0fch, #0fbh, #0fbh, #0fah, #0f9h, #0f8h, #0f7h, #0f6h, 
	.db #0f5h, #0f4h, #0f2h, #0f1h, #0efh, #0eeh, #0ech, #0ebh, 
	.db #0e9h, #0e7h, #0e5h, #0e4h, #0e2h, #0e0h, #0ddh, #0dbh, 
	.db #0d9h, #0d7h, #0d5h, #0d2h, #0d0h, #0cdh, #0cbh, #0c8h, 
	.db #0c6h, #0c3h, #0c1h, #0beh, #0bbh, #0b8h, #0b6h, #0b3h, 
	.db #0b0h, #0adh, #0aah, #0a7h, #0a4h, #0a1h, #09eh, #09bh, 
	.db #098h, #095h, #092h, #08fh, #08bh, #088h, #085h, #082h, 
	.db #07fh, #07ch, #079h, #076h, #073h, #06fh, #06ch, #069h, 
	.db #066h, #063h, #060h, #05dh, #05ah, #057h, #054h, #051h, 
	.db #04eh, #04bh, #048h, #046h, #043h, #040h, #03dh, #03bh, 
	.db #038h, #036h, #033h, #031h, #02eh, #02ch, #029h, #027h, 
	.db #025h, #023h, #021h, #01eh, #01ch, #01ah, #019h, #017h, 
	.db #015h, #013h, #012h, #010h, #00fh, #00dh, #00ch, #00ah, 
	.db #009h, #008h, #007h, #006h, #005h, #004h, #003h, #003h, 
	.db #002h, #001h, #001h, #000h, #000h, #000h, #000h, #000h, 
	.db #000h, #000h, #000h, #000h, #000h, #000h, #001h, #001h, 
	.db #002h, #003h, #003h, #004h, #005h, #006h, #007h, #008h, 
	.db #009h, #00ah, #00ch, #00dh, #00fh, #010h, #012h, #013h, 
	.db #015h, #017h, #019h, #01ah, #01ch, #01eh, #021h, #023h, 
	.db #025h, #027h, #029h, #02ch, #02eh, #031h, #033h, #036h, 
	.db #038h, #03bh, #03dh, #040h, #043h, #046h, #048h, #04bh, 
	.db #04eh, #051h, #054h, #057h, #05ah, #05dh, #060h, #063h, 
	.db #066h, #069h, #06ch, #06fh, #073h, #076h, #079h, #07ch,

