from math import sin, pi
 
def hex_format( n ):
	return '#{:03x}h'.format( n )

def hexsin():
	for t in range( 256 ):
		yield hex_format( int( 255 * ( 1 + sin( t * pi / 128 ) ) / 2 ) )

def collect( gen, n ):
	temp = []
	for entry in gen():
		temp.append( entry )
		if len( temp ) == n:
			yield temp
			temp = []
	if len( temp ) > 0:
		yield temp
print ";", "#"*60
print "; Autogenerated sin table made in python"
print ";", "#"*60
print ""
print "sintable:"
for line in collect( hexsin, 8 ):
	print "\t.db",
	for x in line:
		print x + ",",
	print ""
